/**
 * F3 Learning Queue rule engine.
 *
 * Phase 1 contract (PRD §B-4):
 *   1. Pick weakest QuestionType (predictCorrectness ascending)
 *   2. Look up that QuestionType's dominant dimensions (top 2 by weight)
 *   3. Pick 10 vocab items whose dimension matches + IRT b in [theta-0.4, theta+0.4]
 *   4. (Future) attach 1 passage matched by topic + difficulty
 *
 * Data source (2026-05-23 update):
 *   - VOCAB_POOL: 486 cards / 484 unique lemmas from vocabulary-db
 *     (irt-5D-vocab-db-4opt-filtered.csv) generated by scripts/build-vocab-pool.mjs.
 *     Replaces former POOL (30 cards / 15 lemmas).
 *   - C4.2 diversity now meaningful with 32x larger lemma space.
 */

import type { DiagnosticInput, VocabDimension } from "./diagnostic";
import { QUESTION_TYPES, predictCorrectness, type QuestionType } from "./ontology";
import { VOCAB_POOL, type VocabCard } from "./vocabulary-pool";

// Re-export VocabCard for backward compatibility with existing imports.
export type { VocabCard };

/**
 * Pool source: imported VOCAB_POOL from lib/vocabulary-pool.ts
 * (486 cards / 484 unique lemmas, balanced D1-D5 × 7 difficulty bands).
 */
const POOL: VocabCard[] = VOCAB_POOL;

// ─── Queue selection ──────────────────────────────────────────────

export interface QueuePlan {
  /** Targeted weakest QuestionType */
  targetQuestionType: QuestionType;
  /** Predicted correctness (0-1) on that type — lower = weaker */
  predictedCorrectness: number;
  /** Dimensions chosen (top 2 by weight in the target QT) */
  targetDimensions: VocabDimension[];
  /** The vocab cards selected (length = sessionSize, may be < if pool exhausted) */
  cards: VocabCard[];
}

export interface QueueOpts {
  sessionSize?: number;
  /** Width of IRT b window around theta */
  difficultyHalfWidth?: number;
  /** Avoid these itemIds (V3 only — passed to ContentGenerator) */
  excludeItemIds?: string[];
}

/**
 * Build a learning queue from a diagnostic.
 * Deterministic given (diagnostic + RNG seed if shuffled).
 */
export function buildQueue(
  diag: DiagnosticInput,
  opts: QueueOpts = {}
): QueuePlan {
  const sessionSize = opts.sessionSize ?? 10;
  const halfWidth = opts.difficultyHalfWidth ?? 0.4;

  // 1. Weakest QuestionType
  const ranked = QUESTION_TYPES.map((qt) => ({
    qt,
    p: predictCorrectness(diag.dimensionScores, qt),
  })).sort((a, b) => a.p - b.p);
  const target = ranked[0];

  // 2. Top-2 dimensions by weight
  const dimsRanked = (Object.entries(target.qt.weights) as Array<[VocabDimension, number]>)
    .sort((a, b) => b[1] - a[1])
    .map(([d]) => d);
  const targetDims = dimsRanked.slice(0, 2);

  // 3. Filter pool by dimension + difficulty window
  const bMin = diag.theta - halfWidth;
  const bMax = diag.theta + halfWidth;
  let candidates = POOL.filter(
    (c) =>
      targetDims.includes(c.dimension) && c.difficulty >= bMin && c.difficulty <= bMax
  );

  // Window expansion if too few (recursive fallback) — keep simple, single retry
  if (candidates.length < sessionSize) {
    const wider = POOL.filter(
      (c) =>
        targetDims.includes(c.dimension) &&
        c.difficulty >= bMin - 0.6 &&
        c.difficulty <= bMax + 0.6
    );
    candidates = wider;
  }

  // 4. Balanced by dimension. Within each dim:
  //    (a) order by closeness to theta (most informative first)
  //    (b) take 2× the slot count as a tie-break candidate set
  //    (c) shuffle and slice — adds diversity across repeat calls (C4.2 mechanism)
  const cards: VocabCard[] = [];
  const slotsPerDim = Math.ceil(sessionSize / targetDims.length);
  for (const dim of targetDims) {
    const ranked = candidates
      .filter((c) => c.dimension === dim)
      .sort(
        (a, b) =>
          Math.abs(a.difficulty - diag.theta) - Math.abs(b.difficulty - diag.theta)
      )
      .slice(0, slotsPerDim * 2);
    // Fisher-Yates shuffle (non-deterministic Math.random) — gives queue
    // diversity across repeat calls for the same diagnostic.
    for (let i = ranked.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [ranked[i], ranked[j]] = [ranked[j], ranked[i]];
    }
    cards.push(...ranked.slice(0, slotsPerDim));
  }

  return {
    targetQuestionType: target.qt,
    predictedCorrectness: target.p,
    targetDimensions: targetDims,
    cards: cards.slice(0, sessionSize),
  };
}

/**
 * Returns the unique dimensions present in a queue (for summary display).
 */
export function dimensionsInQueue(cards: VocabCard[]): VocabDimension[] {
  return Array.from(new Set(cards.map((c) => c.dimension)));
}

// ─── V2: Thompson sampling integration (P-1 W3) ────────────────────

import type { BetaPosterior, ConfidenceLevel } from "./recommendation";
import { recommendQuestionType, findExplorationTarget } from "./recommendation";

export interface QueuePlanV2 extends QueuePlan {
  /** Confidence in the target QT selection */
  confidence: ConfidenceLevel;
  /** Algorithm used (rule-v1-fallback when posterior data insufficient) */
  algorithm: "rule-v1-fallback" | "thompson-v2";
  /** Runner-up target (top-2 by sampled θ) — useful when confidence is low */
  alternateQuestionType: QuestionType;
  /** Sampled θ value for the chosen target (rule-v1: predictCorrectness) */
  targetThetaSample: number;
}

/**
 * V2 queue builder — replaces deterministic argmin(predictCorrectness) with
 * Thompson sampling over Beta posteriors.
 *
 * Card selection (dim filter, b window, shuffle) is identical to V1 once
 * the target QuestionType is chosen.
 *
 * Pure function: posteriors are passed in by the caller (typically loaded
 * from lib/recommendation-store.ts at page level).
 */
export function buildQueueV2(
  diag: DiagnosticInput,
  posteriors: Record<string, BetaPosterior>,
  opts: QueueOpts = {}
): QueuePlanV2 {
  const sessionSize = opts.sessionSize ?? 10;
  const halfWidth = opts.difficultyHalfWidth ?? 0.4;

  // 1. Thompson recommendation (or rule-v1 fallback)
  const rec = recommendQuestionType(diag.dimensionScores, posteriors);
  const target = rec.targetQuestionType;

  // 2. Top-2 dimensions by weight (unchanged from V1)
  const dimsRanked = (Object.entries(target.weights) as Array<[VocabDimension, number]>)
    .sort((a, b) => b[1] - a[1])
    .map(([d]) => d);
  const targetDims = dimsRanked.slice(0, 2);

  // 3. Filter pool + difficulty window (identical to V1)
  const bMin = diag.theta - halfWidth;
  const bMax = diag.theta + halfWidth;
  let candidates = POOL.filter(
    (c) => targetDims.includes(c.dimension) && c.difficulty >= bMin && c.difficulty <= bMax
  );
  if (candidates.length < sessionSize) {
    candidates = POOL.filter(
      (c) =>
        targetDims.includes(c.dimension) &&
        c.difficulty >= bMin - 0.6 &&
        c.difficulty <= bMax + 0.6
    );
  }

  // 4. Closeness sort + shuffle (V1 diversity mechanism)
  const cards: VocabCard[] = [];
  const slotsPerDim = Math.ceil(sessionSize / targetDims.length);
  for (const dim of targetDims) {
    const ranked = candidates
      .filter((c) => c.dimension === dim)
      .sort(
        (a, b) =>
          Math.abs(a.difficulty - diag.theta) - Math.abs(b.difficulty - diag.theta)
      )
      .slice(0, slotsPerDim * 2);
    for (let i = ranked.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [ranked[i], ranked[j]] = [ranked[j], ranked[i]];
    }
    cards.push(...ranked.slice(0, slotsPerDim));
  }

  return {
    targetQuestionType: target,
    predictedCorrectness: rec.targetThetaSample,
    targetDimensions: targetDims,
    cards: cards.slice(0, sessionSize),
    confidence: rec.confidence,
    algorithm: rec.algorithm,
    alternateQuestionType: rec.alternateQuestionType,
    targetThetaSample: rec.targetThetaSample,
  };
}

// ─── V3: ContentGenerator integration (P-2 W4) ──────────────────────

import type { ContentGenerator } from "./content-generator";
import type { ValidatorIssue } from "./content-validators";

export interface QueuePlanV3 extends QueuePlanV2 {
  /** Which generator produced the cards (for analytics + analytics-events) */
  generator: string;
  /** Validation issues encountered during generation (errors filtered out) */
  generatorIssues: ValidatorIssue[];
  /**
   * "exploration" if useExploration option overrode primary target.
   * "primary" otherwise. UI uses this to badge the queue source.
   */
  selectionMode?: "primary" | "exploration";
}

export interface QueueV3Opts extends QueueOpts {
  /**
   * Override primary target with exploration target (least-known QT).
   * When true and exploration target exists, queue uses that QT instead.
   * Falls back to primary if no exploration target available.
   *
   * Phase 2 P-1 W9: adaptive frequency policy lives in caller — this is
   * a binary toggle. See docs/02-design/phase2-p1-recommendation-w9-exploration.md
   */
  useExploration?: boolean;
}

/**
 * V3 queue builder — Thompson QT selection + ContentGenerator card production.
 *
 * Replaces V2's hard-coded VOCAB_POOL filter with a pluggable generator.
 * Default generator = defaultGeneratorChain (EBS-demo → LocalPool fallback).
 *
 * Async because EBS-demo path involves a REST call. LocalPoolGenerator path
 * still resolves synchronously (just wrapped in Promise.resolve).
 *
 * When opts.useExploration is true and findExplorationTarget returns a
 * non-null candidate, that QT replaces the primary target. The selectionMode
 * field tells callers whether exploration was actually used.
 */
export async function buildQueueV3(
  diag: DiagnosticInput,
  posteriors: Record<string, BetaPosterior>,
  generator: ContentGenerator,
  opts: QueueV3Opts = {}
): Promise<QueuePlanV3> {
  const sessionSize = opts.sessionSize ?? 10;
  const halfWidth = opts.difficultyHalfWidth ?? 0.4;

  // 1. Thompson recommendation (primary)
  const rec = recommendQuestionType(diag.dimensionScores, posteriors);
  let target = rec.targetQuestionType;
  let selectionMode: "primary" | "exploration" = "primary";

  // 1b. Exploration override (Phase 2 P-1 W9)
  if (opts.useExploration) {
    const exp = findExplorationTarget(posteriors, {
      excludeQtIds: [rec.targetQuestionType.id, rec.alternateQuestionType.id],
    });
    if (exp) {
      target = exp.questionType;
      selectionMode = "exploration";
    }
    // If exp is null (all well-explored), fall through to primary
  }

  // 2. Top-2 dimensions by weight
  const dimsRanked = (Object.entries(target.weights) as Array<[VocabDimension, number]>)
    .sort((a, b) => b[1] - a[1])
    .map(([d]) => d);
  const targetDims = dimsRanked.slice(0, 2);

  // 3. Delegate card production to generator
  const generated = await generator.generate({
    qtId: target.id,
    targetDimensions: targetDims,
    difficultyRange: { min: diag.theta - halfWidth, max: diag.theta + halfWidth },
    count: sessionSize,
    excludeItemIds: opts.excludeItemIds,
  });

  return {
    targetQuestionType: target,
    predictedCorrectness: rec.targetThetaSample,
    targetDimensions: targetDims,
    cards: generated.cards,
    confidence: rec.confidence,
    algorithm: rec.algorithm,
    alternateQuestionType: rec.alternateQuestionType,
    targetThetaSample: rec.targetThetaSample,
    generator: generated.generator,
    generatorIssues: generated.issues,
    selectionMode,
  };
}
